openapi: 3.0.2
info:
  title: Random User API
  description: >-
    The Random API provides a free service to generate random user data for
    application testing. 
  version: '2.5'
  termsOfService: https://openweathermap.org/terms
  contact:
    name: Random User API
    url: https://randomuser.me/
    email: some_email@gmail.com
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: https://randomuser.me/
servers:
  - url: https://randomuser.me/
externalDocs:
  description: Documentation for the Random User API
  url: https://randomuser.me/documentation
paths:
  /api:
    $ref: paths/api.yaml
